# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-16 15:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LinkedinSearch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_company', models.CharField(max_length=120, verbose_name='Search term')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date created')),
            ],
        ),
        migrations.CreateModel(
            name='LinkedinSearchResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=120, verbose_name='Full name')),
                ('title', models.CharField(max_length=250, verbose_name='Title')),
                ('search', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inapp.LinkedinSearch', verbose_name='Linkedin Search instance')),
            ],
        ),
    ]
