# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-17 12:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='linkedinsearch',
            name='company_id',
            field=models.IntegerField(default=None, null=True, verbose_name='Linkedin company ID'),
        ),
    ]
