# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-17 15:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inapp', '0002_linkedinsearch_company_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='linkedinsearch',
            name='status',
            field=models.SmallIntegerField(choices=[(1, 'Search in process'), (2, 'Search is finished'), (3, 'Search has errors')], default=1, verbose_name='Status of search'),
        ),
    ]
