# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-17 15:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inapp', '0003_linkedinsearch_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='linkedinsearch',
            old_name='company_id',
            new_name='companyId',
        ),
    ]
