# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-21 14:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inapp', '0004_auto_20170317_1529'),
    ]

    operations = [
        migrations.CreateModel(
            name='LinkedinUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=120, verbose_name='Linkedin email')),
                ('password', models.CharField(max_length=120, verbose_name='Linkedin password')),
            ],
        ),
    ]
