# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-27 19:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inapp', '0005_linkedinuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='linkedinuser',
            name='verification_code',
            field=models.CharField(default=None, max_length=30, null=True, verbose_name='Linkedin verification code'),
        ),
        migrations.AlterField(
            model_name='linkedinsearch',
            name='status',
            field=models.SmallIntegerField(choices=[(1, 'Search in process'), (2, 'Search is finished'), (3, 'Search has errors'), (4, 'Linkedin user is not logged in'), (5, 'Linkedin user has been authenticated'), (6, 'Linkedin verification code is not valid')], default=1, verbose_name='Status of search'),
        ),
    ]
