# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-28 06:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inapp', '0006_auto_20170327_1936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linkedinsearch',
            name='status',
            field=models.SmallIntegerField(choices=[(1, 'Search in process'), (2, 'Search is finished'), (3, 'Search has errors'), (4, 'Linkedin user is not logged in'), (5, 'Linkedin user has been authenticated'), (6, 'Linkedin asks verification code'), (7, 'Linkedin verification code is not valid')], default=1, verbose_name='Status of search'),
        ),
    ]
