# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-03 06:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inapp', '0009_auto_20170328_2229'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='linkedinsearchresult',
            name='full_name',
        ),
        migrations.AddField(
            model_name='linkedinsearchresult',
            name='first_name',
            field=models.CharField(blank=True, default=None, max_length=120, null=True, verbose_name='First name'),
        ),
        migrations.AddField(
            model_name='linkedinsearchresult',
            name='last_name',
            field=models.CharField(blank=True, default=None, max_length=120, null=True, verbose_name='Last name'),
        ),
    ]
