# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-06 06:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inapp', '0010_auto_20170403_0627'),
    ]

    operations = [
        migrations.AddField(
            model_name='linkedinsearchresult',
            name='location',
            field=models.CharField(blank=True, default=None, max_length=250, null=True, verbose_name='Location'),
        ),
    ]
