# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-12 17:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inapp', '0013_auto_20170412_1648'),
    ]

    operations = [
        migrations.RenameField(
            model_name='linkedinsearch',
            old_name='search_company',
            new_name='search_term',
        ),
    ]
