# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-13 05:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inapp', '0014_auto_20170412_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linkedinsearch',
            name='search_type',
            field=models.SmallIntegerField(choices=[(1, 'Search by company or company ID'), (2, 'Search by Geo')], default=1, verbose_name='Search type'),
        ),
    ]
