# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-14 07:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inapp', '0016_linkedinsearch_search_geo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linkedinsearchresult',
            name='title',
            field=models.CharField(blank=True, default=None, max_length=250, null=True, verbose_name='Title'),
        ),
    ]
