# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-19 12:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inapp', '0017_auto_20170414_0729'),
    ]

    operations = [
        migrations.AddField(
            model_name='linkedinsearchresult',
            name='current_company',
            field=models.CharField(blank=True, default=None, max_length=250, null=True, verbose_name='Current company'),
        ),
    ]
