# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-10 20:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inapp', '0020_auto_20170505_0849'),
    ]

    operations = [
        migrations.AddField(
            model_name='linkedinsearch',
            name='last_scraped_page',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='Last scraped employees page'),
        ),
    ]
